//
// Created by jo on 2020/08/27.
//

#ifndef ABSTRACTFACTORY_SHAPESABSTRACTFACTORY_H
#define ABSTRACTFACTORY_SHAPESABSTRACTFACTORY_H


class ShapesAbstractFactory {

};


#endif //ABSTRACTFACTORY_SHAPESABSTRACTFACTORY_H
